/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "theme-primary": "var(--color-theme-primary)",
        "theme-secondary": "var(--color-theme-secondary)",
        "theme-tertiary": "var(--color-theme-tertiary)",
        "theme-explain": "var(--color-theme-explain)",
        "theme-invert": "var(--color-theme-invert)",
        "theme-highlight": "var(--color-theme-highlight)",
        "theme-disabled": "var(--color-theme-disabled)",
        "theme-neutral": "var(--color-theme-neutral)",
        "theme-overlay": "var(--color-theme-overlay)",
        "theme-scroll": "var(--color-theme-scroll)",
        "theme-crimson": "var(--color-theme-crimson)",
        "theme-buy": "var(--color-theme-buy)",
        "theme-sell": "var(--color-theme-sell)",
        "theme-ref": "var(--color-theme-ref)",
        "theme-switch": "var(--color-theme-switch)",
        "theme-buy-highlight": "var(--color-theme-buy-highlight)",
        "theme-sell-highlight": "var(--color-theme-sell-highlight)",
        "theme-ref-highlight": "var(--color-theme-ref-highlight)",
        "theme-text-primary": "var(--color-theme-text-primary)",
        "theme-text-secondary": "var(--color-theme-text-secondary)",
        "theme-text-tertiary": "var(--color-theme-text-tertiary)",
        "theme-text-explain": "var(--color-theme-text-explain)",
        "theme-text-invert": "var(--color-theme-text-invert)",
        "theme-text-highlight": "var(--color-theme-text-highlight)",
        "theme-text-up": "var(--color-theme-text-up)",
        "theme-text-down": "var(--color-theme-text-down)",
        "theme-text-ceil": "var(--color-theme-text-ceil)",
        "theme-text-floor": "var(--color-theme-text-floor)",
        "theme-text-ref": "var(--color-theme-text-ref)",
        "theme-text-stable": "var(--color-theme-text-stable)",
        "theme-text-pending": "var(--color-theme-text-pending)",
        "theme-text-success": "var(--color-theme-text-success)",
        "theme-text-fail": "var(--color-theme-text-fail)",
        "theme-text-cancel": "var(--color-theme-text-cancel)",
        "theme-text-disabled": "var(--color-theme-text-disabled)",
        "theme-flash-up": "var(--color-theme-flash-up)",
        "theme-flash-down": "var(--color-theme-flash-down)",
        "theme-flash-ceil": "var(--color-theme-flash-ceil)",
        "theme-flash-floor": "var(--color-theme-flash-floor)",
        "theme-flash-ref": "var(--color-theme-flash-ref)",
        "theme-flash-stable": "var(--color-theme-flash-stable)",
        "theme-price-board-menu": "var(--color-theme-price-board-menu)",
        "theme-price-table-header": "var(--color-theme-price-table-header)",
        "theme-price-table-border": "var(--color-theme-price-table-border)",
        "theme-price-table-col-highlight":
          "var(--color-theme-price-table-col-highlight)",
        "theme-price-table-row-odd": "var(--color-theme-price-table-row-odd)",
        "theme-price-table-row-even": "var(--color-theme-price-table-row-even)",
        "theme-table-header": "var(--color-theme-table-header)",
        "theme-table-row-odd": "var(--color-theme-table-row-odd)",
        "theme-table-row-even": "var(--color-theme-table-row-even)",
        "theme-table-border": "var(--color-theme-table-border)",
        "theme-input-border": "var(--color-theme-input-border)",
        "theme-input-background": "var(--color-theme-input-background)",
        "theme-input-disabled": "var(--color-theme-input-disabled)",
        "theme-tooltip-text-color": "var(--color-theme-tooltip-text-color)",
        "theme-tooltip-background": "var(--color-theme-tooltip-background)",
        "theme-dropdown-background": "var(--color-theme-dropdown-background)",
        "theme-dropdown-active": "var(--color-theme-dropdown-active)",
        "theme-panel-background": "var(--color-theme-panel-background)",
        "theme-toast-background-default":
          "var(--color-theme-toast-background-default)",
        "theme-toast-background-info":
          "var(--color-theme-toast-background-info)",
        "theme-toast-background-success":
          "var(--color-theme-toast-background-success)",
        "theme-toast-background-warning":
          "var(--color-theme-toast-background-warning)",
        "theme-toast-background-error":
          "var(--color-theme-toast-background-error)",
        "theme-toast-background-error":
          "var(--color-classic-price-table-border)",
          
      },
    },
  },
  plugins: [],
};
